AWSTemplateFormatVersion: 2010-09-09
Parameters:
  BucketName:
    Description: Name of S3 Bucket
    Type: String
  BucketName2:
    Description: Name of S3 Bucket
    Type: String
  BucketName3:
    Description: Name of S3 Bucket
    Type: String
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName:
        Ref: BucketName
  S3Bucket2:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName:
        Ref: BucketName2
  S3Bucket3:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName:
        Ref: BucketName3

Outputs:
  S3BucketName:
    Value: !Ref S3Bucket
    Description: Name of S3 bucket