---
- hosts: webservers
  vars:
    http_port: 80
    max_clients: 200
    remote_user: ec2-user
  tasks:
  - name: install the latest version of Apache
    yum:
      name: httpd
      state: latest
  - name: ensure git is at the latest version
    yum:
      name: git
      state: latest
  - name: ensure apache is running
    service:
      name: httpd
      state: started
  - name: ensure git is latest version
    git:
      repo: 'https://github.com/mohanraz81/webtest'
      dest: /var/www/html
      version: master
